### ISSUE TITLE
Support Discord's new updater

### ISSUE THREAD

**Issue by CanadaHonk** [GooseMod/GooseUpdate#2]
Discord has been developing a new updater API for a couple months and they finally seem to be rolling it out to some builds. It defaults to Discord's own as the `settings.json` variable is named differently.

Discord versions already using:
 - Windows Canary (since 19/12-ish)

Progress:
 - [x] Investigate source code
 - [x] Discover endpoints
 - [x] Setup basic redirect for all endpoints
 - [x] Setup basic proxy for module downloading
 - [x] Setup dynamic procedural patching of modules when downloading

**Comment by CanadaHonk** [comment]
Progress is blocked as only build which currently uses it is Windows Canary which I cannot test.

**Comment by lzcunt** [comment]
Progress is no longer blocked 😉

**Comment by CanadaHonk** [comment]
Updates:
- Implementation 1 for API 2 was finished two days ago.
- Implementation 2 for API 2 was (mostly) finished yesterday.
  - Im.2 is vastly different than Im.1, Im.2 uses separate modules per mod and only patches `desktop_core` to require `index.js`'s from those modules for various reasons

**Comment by CanadaHonk** [comment]
This is essentially 90% completed, just needs more wide spread testing before this can be completely closed.

**Comment by CanadaHonk** [comment]
Essentially no issues have been reported in >a month. Closing.
